---
- hosts: localhost
  tasks:

        - name: Update and upgrade apt packages
          become: true
          apt:
            upgrade: yes
            update_cache: yes
            cache_valid_time: 86400 #One day
                       
        - name: Install packages
          apt:
            name:
            - vim
            - git
            - screen
            - curl
            - zsh
            - tmux
            - stow
            - tree
          become: yes
        
        - set_fact:
            HOME={{ansible_env.HOME}}

        # - name: configure tmux
        #   copy:
        #     dest: "{{HOME}}/.tmux.conf"
        #     content: |
        #         set -g mouse on

        # - name: source  tmux
        #   shell: tmux source-file {{HOME}}/.tmux.conf


        - name: Clone dotfiles git repository
          git:
            repo: 'https://github.com/shyamalns/dotfiles.git'
            dest: "{{HOME}}/dotfiles"
            version: beta

        ## Comment after first run
        - name: Install oh-my-zsh shell
         shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

        - name: change shell
          shell: sudo chsh -s `which zsh` `whoami`


        - name: Clone zsh autosuggestions git repository
          git:
            repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
            dest: "{{HOME}}/.oh-my-zsh/plugins/zsh-autosuggestions"

        - name: Clone zsh highlighting repository
          git:
            repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
            dest: "{{HOME}}/.oh-my-zsh/plugins/zsh-syntax-highlighting"

